### PR TITLE
[ci skip] [skip ci] ***NO_CI*** Use @conda-forge/terraform as maintainers

### PR DESCRIPTION
**Pull request by sodre**

### CODE REVIEW

**Comment by dhirschfeld** [comment]
You'd think that would have been enough to skip the CI eh?

**Comment by dhirschfeld** [comment]
I think the `@` is causing issues:
```
extra:
  recipe-maintainers:
    - @conda-forge/terraform
    - dhirschfeld

----------------------------------------------------------------------
Unable to parse meta.yaml file
```

**Comment by sodre** [comment]
Fixing it now . I should have tried to render it locally first. 

The build will almost certainly fail until we get golang updated.

**Comment by dhirschfeld** [comment]
Looks like there are a few PR over there which aren't passing CI:
https://github.com/conda-forge/go-feedstock/pulls

**Comment by dhirschfeld** [comment]
I guess if you're doing a re-render you'd want the CI to actually run? And therefore bump the build number?

**Comment by sodre** [comment]
The rerender was just to update the code owners, I’m fine letting the builds fail in the master branch for the time being. 

Does that make sense to you?

**Pull request merged**
