### PR TITLE
Update to 2.5.0

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Not sure what's going on with OSX:
```
Solving environment: ...working... failed
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1838, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 757, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 2054, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 727, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 561, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/environ.py", line 764, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 289, in solve_final_state
    self.determine_constricting_specs(spec, ssc.solution_precs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda/core/solve.py", line 315, in determine_constricting_specs
    if sp.name == spec.name][0]
IndexError: list index out of range
```

...or linux
```
github.com/terraform-providers/terraform-provider-azurerm/azurerm
github.com/terraform-providers/terraform-provider-azurerm
go build github.com/terraform-providers/terraform-provider-azurerm: open /terraform-provider-azurerm_v2.5.0_x4: permission denied
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/terraform-provider-azurerm_1586866024914/work/conda_build.sh']' returned non-zero exit status 1.
```

Will try again... 🤞

**Comment by dhirschfeld** [comment]
Same result :(
* Permission denied on linux
* Failure to solve & conda internal error on OSX

**Comment by dhirschfeld** [comment]
Ping @conda-forge/terraform any ideas?

**Comment by rluria14** [comment]
@conda-forge-admin, please restart ci

**Comment by sodre** [comment]
The issue is that the recipe is using the GOBIN environment variable directly.  This was dropped in the latest versions of the go compilers. 

You can obtain the GOBIN env value by calling ‘go env GOBIN’

Whatever fix you decide try to script it because there are about 70 recipes.

**Comment by dhirschfeld** [comment]
> *Whatever fix you decide try to script it because there are about 70 recipes*

😬 

Thanks for the info @sodre - will have to think how to approach that...

**Comment by dhirschfeld** [comment]
Does this affect *all* go compiler recipes or just `terraform-provider-*-feedstock`?

**Comment by dhirschfeld** [comment]
Setting:
```bash
GOBIN=$(go env GOBIN)  # [not win]
```
...seems to have fixed linux.

OSX is still failing with an internal conda error.

Since I need this on Windows I'm inclined to merge without OSX support and add it back in after https://github.com/conda/conda/issues/9845 is resolved.

**Comment by rluria14** [comment]
@dhirschfeld thank you for fixing this! since this is an overarching solution to the `terraform-provider-*-feedstock's`, is there a bot that we could generate to add `GOBIN=$(go env GOBIN)  # [not win]` to each recipe??

**Comment by dhirschfeld** [comment]
I don't know of any automated way to do that

**Comment by beckermr** [comment]
Yes. Since we need a rerender, we need to make a custom migration in regro/cf-scripts. Please open an issue there. cc @conda-forge/bot

**Comment by dhirschfeld** [comment]
So, this is a horrific hack - I've pinned `conda` on OSX to 4.7.5 which predates the changes in https://github.com/conda/conda/pull/8899 which appears to have introduced a bug - https://github.com/conda/conda/issues/9845

However, everything does build and I need this on Windows so I'm inclined to merge with the hack in-place until the bug can be fixed.

I'm off for now, if there are no objections to the plan I'll merge in the morning...

**Comment by rluria14** [comment]
@dhirschfeld @beckermr Understood. It might be best to hold off creating an autobot for all the terraform-provider-*-feedstocks until the osx bug is fixed

**Comment by dhirschfeld** [comment]
I've opened an issue on the `conda` repo (linked above) and have brought up the problem on both the `conda` and `conda-forge` gitters:
- https://gitter.im/conda/conda?at=5e97007f85b01628f04cc9d2
- https://gitter.im/conda-forge/conda-forge.github.io?at=5e97a222c38aa05a1a758a94

So hopefully someone with a mac can debug the underlying issue. If no one beats me to it I can try and figure it out this evening...

**Pull request merged**
